# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nicolas Schmelling
tagline:          'Blog'
description:      ''
url:              http://schmelling.github.io
baseurl:          /

author:
  name:           'Nicolas Schmelling'
  url:            https://twitter.com/bio_mediocre

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/schmelling/schmelling.github.io
